<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="DB\Context\" />
      <Folder Include="Entities\" />
      <Folder Include="Repositories\" />
      <Folder Include="Topology_Services\" />
    </ItemGroup>

</Project>
